from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path
from typing import Any

import pandas as pd

from agents import PROJECT_ROOT
from agents.schemas import AgentPlan, AgentRequest, AgentResult, AgentStep
from agents.trace_logger import log_agent_run
from agents.router_agent import route_request


DEMO_CASES_DIR = PROJECT_ROOT / "data" / "demo_cases"
RUN_METADATA_PATH = PROJECT_ROOT / "outputs" / "run_metadata.json"
APPLY_RAW_CASE_SCRIPT = PROJECT_ROOT / "scripts" / "apply_raw_case.py"
RUN_PIPELINE_SCRIPT = PROJECT_ROOT / "run_pipeline.py"
ALLOWED_CASES = {"baseline_original", "apparel_vip_shift"}


def _relative(path: Path) -> str:
    return str(path.relative_to(PROJECT_ROOT)).replace("\\", "/")


def _ensure_project_path(path: Path) -> Path:
    resolved = path.resolve()
    project_root = PROJECT_ROOT.resolve()
    if resolved != project_root and project_root not in resolved.parents:
        raise ValueError(f"Path is outside project root: {path}")
    return resolved


def _detect_case_name(question: str) -> str:
    normalized = question.lower()
    for case_name in sorted(ALLOWED_CASES):
        if case_name.lower() in normalized:
            return case_name
    return "apparel_vip_shift"


def _list_demo_cases() -> tuple[str, dict[str, Any]]:
    _ensure_project_path(DEMO_CASES_DIR)
    cases = []
    if DEMO_CASES_DIR.exists():
        for case_dir in sorted(DEMO_CASES_DIR.iterdir()):
            if case_dir.is_dir() and (case_dir / "raw.csv").exists():
                cases.append(case_dir.name)

    answer = "Available demo cases:\n" + "\n".join(f"- {case}" for case in cases)
    return answer, {"cases": cases}


def _compare_demo_cases() -> tuple[str, dict[str, Any]]:
    baseline_path = _ensure_project_path(DEMO_CASES_DIR / "baseline_original" / "customer_segments.csv")
    apparel_path = _ensure_project_path(DEMO_CASES_DIR / "apparel_vip_shift" / "customer_segments.csv")

    baseline = pd.read_csv(baseline_path)
    apparel = pd.read_csv(apparel_path)

    merged = baseline[["segment", "customer_count", "share", "weighted_aov"]].merge(
        apparel[["segment", "customer_count", "share", "weighted_aov"]],
        on="segment",
        suffixes=("_baseline", "_apparel_shift"),
    )
    merged["customer_count_delta"] = (
        merged["customer_count_apparel_shift"] - merged["customer_count_baseline"]
    )
    merged["weighted_aov_delta"] = (
        merged["weighted_aov_apparel_shift"] - merged["weighted_aov_baseline"]
    ).round(2)

    lines = [
        "Segment comparison: baseline_original -> apparel_vip_shift",
        "",
        "| Segment | Baseline customers | Apparel shift customers | Customer delta | Baseline AOV | Apparel shift AOV | AOV delta |",
        "|---|---:|---:|---:|---:|---:|---:|",
    ]
    for row in merged.to_dict(orient="records"):
        lines.append(
            "| {segment} | {customer_count_baseline} | {customer_count_apparel_shift} | "
            "{customer_count_delta:+d} | {weighted_aov_baseline:.2f} | "
            "{weighted_aov_apparel_shift:.2f} | {weighted_aov_delta:+.2f} |".format(
                **row
            )
        )

    return "\n".join(lines), {"comparison": merged.to_dict(orient="records")}


def _workflow_status() -> tuple[str, dict[str, Any]]:
    metadata_path = _ensure_project_path(RUN_METADATA_PATH)
    if not metadata_path.exists():
        return "No workflow metadata found at outputs/run_metadata.json.", {}

    metadata = json.loads(metadata_path.read_text(encoding="utf-8"))
    answer = "\n".join(
        [
            "Current workflow status:",
            f"- run_time_utc: {metadata.get('run_time_utc')}",
            f"- requested_provider: {metadata.get('requested_provider')}",
            f"- provider: {metadata.get('provider')}",
            f"- model: {metadata.get('model')}",
            f"- api_reached: {metadata.get('api_reached')}",
            f"- validation_passed: {metadata.get('validation_passed')}",
            f"- fallback_used: {metadata.get('fallback_used')}",
            f"- retry_count: {metadata.get('retry_count')}",
            f"- error_type: {metadata.get('error_type')}",
            f"- raw_row_count: {metadata.get('raw_row_count')}",
            f"- processed_customer_count: {metadata.get('processed_customer_count')}",
        ]
    )

    return answer, {"metadata": metadata}


def _explain_powerbi_workflow() -> tuple[str, dict[str, Any]]:
    answer = "\n".join(
        [
            "Power BI workflow:",
            "- Main BI visuals should read data/processed/fact_user_behavior_scored.csv.",
            "- AI Insight Box should read outputs/powerbi_llm_insights.csv.",
            "- Both files are generated by the same V3 pipeline, so segment counts stay aligned.",
            "- If chart counts differ from the AI Insight Box, Power BI is usually still connected to an old table or old segment field.",
            "- After running the workflow, open the PBIX file and click Home -> Refresh.",
        ]
    )
    return answer, {}


def _run_workflow(plan: AgentPlan, request: AgentRequest) -> tuple[str, dict[str, Any]]:
    case_name = _detect_case_name(plan.question)
    commands = [
        f".venv\\Scripts\\python.exe scripts\\apply_raw_case.py {case_name}",
        ".venv\\Scripts\\python.exe run_pipeline.py --provider mock",
    ]

    if plan.dry_run:
        answer = "\n".join(
            [
                "Dry run only. No files were changed and the pipeline was not executed.",
                "Planned commands:",
                *[f"- {command}" for command in commands],
                "Then refresh Power BI: Home -> Refresh.",
            ]
        )
        return answer, {"case_name": case_name, "commands": commands, "executed": False}

    if request.provider != "mock":
        raise ValueError("Execution mode only allows run_pipeline.py --provider mock in V3.3.")

    apply_script = _ensure_project_path(APPLY_RAW_CASE_SCRIPT)
    pipeline_script = _ensure_project_path(RUN_PIPELINE_SCRIPT)

    apply_result = subprocess.run(
        [sys.executable, str(apply_script), case_name],
        cwd=PROJECT_ROOT,
        check=True,
        capture_output=True,
        text=True,
    )
    pipeline_result = subprocess.run(
        [sys.executable, str(pipeline_script), "--provider", "mock"],
        cwd=PROJECT_ROOT,
        check=True,
        capture_output=True,
        text=True,
    )

    answer = "\n".join(
        [
            f"Executed demo case switch and mock workflow for {case_name}.",
            "Power BI next step: Home -> Refresh.",
        ]
    )
    return answer, {
        "case_name": case_name,
        "commands": commands,
        "executed": True,
        "apply_raw_case_stdout": apply_result.stdout,
        "pipeline_stdout": pipeline_result.stdout,
    }


def _apply_step_outputs(plan: AgentPlan, output: dict[str, Any]) -> list[AgentStep]:
    steps = []
    for step in plan.steps:
        step.status = "completed"
        step.output = output
        steps.append(step)
    return steps


def run_agent_request(request: AgentRequest) -> AgentResult:
    plan = route_request(request)

    if plan.refusal_reason:
        result = AgentResult(
            question=plan.question,
            intent=plan.intent,
            selected_tools=plan.selected_tools,
            risk_level=plan.risk_level,
            requires_execution=plan.requires_execution,
            dry_run=plan.dry_run,
            final_answer=plan.refusal_reason,
            status="refused",
            error=plan.refusal_reason,
            steps=plan.steps,
        )
        result.trace_path = log_agent_run(plan, result)
        return result

    try:
        if plan.intent == "list_demo_cases":
            final_answer, output = _list_demo_cases()
        elif plan.intent == "compare_demo_cases":
            final_answer, output = _compare_demo_cases()
        elif plan.intent == "workflow_status":
            final_answer, output = _workflow_status()
        elif plan.intent == "run_workflow":
            final_answer, output = _run_workflow(plan, request)
        elif plan.intent == "explain_powerbi_workflow":
            final_answer, output = _explain_powerbi_workflow()
        else:
            final_answer = (
                "I could not route this request. Try asking to list demo cases, compare demo cases, "
                "show workflow status, explain the Power BI workflow, or dry-run a workflow switch."
            )
            output = {}

        result = AgentResult(
            question=plan.question,
            intent=plan.intent,
            selected_tools=plan.selected_tools,
            risk_level=plan.risk_level,
            requires_execution=plan.requires_execution,
            dry_run=plan.dry_run,
            final_answer=final_answer,
            status="ok",
            steps=_apply_step_outputs(plan, output),
        )
    except Exception as exc:
        result = AgentResult(
            question=plan.question,
            intent=plan.intent,
            selected_tools=plan.selected_tools,
            risk_level=plan.risk_level,
            requires_execution=plan.requires_execution,
            dry_run=plan.dry_run,
            final_answer=f"Agent run failed: {exc}",
            status="error",
            error=str(exc),
            steps=plan.steps,
        )

    result.trace_path = log_agent_run(plan, result)
    return result
